# Generated by Django 2.0.5 on 2018-05-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('time_start', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('time_end', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('location', models.CharField(max_length=2000)),
                ('details', models.TextField(blank=True, null=True)),
                ('cost', models.CharField(max_length=200)),
                ('event_site', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
